# Copyright (c) 2011 - 2013, SimpleMesh AUTHORS
# Eric Gnoske,
# Colin O'Flynn,
# Blake Leverett,
# Rob Fries,
# Clara Ferrando,
# Colorado Micro Devices Inc..
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
#   1) Redistributions of source code must retain the above copyright notice,
#      this list of conditions and the following disclaimer.
#
#   2) Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in the
#       documentation and/or other materials provided with the distribution.
#
#   3) Neither the name of the SimpleMesh AUTHORS nor the names of its contributors
#       may be used to endorse or promote products derived from this software
#       without specific prior written permission.
#
#  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
#  AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
#  IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
#  ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
#  LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
#  CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
#  SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
#  INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
#  CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
#  ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
#  POSSIBILITY OF SUCH DAMAGE.

# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Dropbox\radioblock\RB_Gui_PS\RB.ui'
#
# Created: Sun Mar 03 02:37:03 2013
#      by: pyside-uic 0.2.14 running on PySide 1.1.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(583, 648)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("favicon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setMaximumSize(QtCore.QSize(1777215, 16777215))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, -1, 70, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self._2 = QtGui.QGridLayout()
        self._2.setHorizontalSpacing(6)
        self._2.setObjectName("_2")
        self.label_6 = QtGui.QLabel(self.tab)
        self.label_6.setObjectName("label_6")
        self._2.addWidget(self.label_6, 0, 0, 1, 1)
        self.comboBoxCOMPort = QtGui.QComboBox(self.tab)
        self.comboBoxCOMPort.setMinimumSize(QtCore.QSize(160, 25))
        self.comboBoxCOMPort.setObjectName("comboBoxCOMPort")
        self._2.addWidget(self.comboBoxCOMPort, 0, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.tab)
        self.label_7.setObjectName("label_7")
        self._2.addWidget(self.label_7, 1, 0, 1, 1)
        self.comboBoxBAUDRate = QtGui.QComboBox(self.tab)
        self.comboBoxBAUDRate.setMinimumSize(QtCore.QSize(80, 25))
        self.comboBoxBAUDRate.setObjectName("comboBoxBAUDRate")
        self._2.addWidget(self.comboBoxBAUDRate, 1, 1, 1, 1)
        self.openComButton = QtGui.QPushButton(self.tab)
        self.openComButton.setMinimumSize(QtCore.QSize(0, 25))
        self.openComButton.setObjectName("openComButton")
        self._2.addWidget(self.openComButton, 2, 0, 1, 1)
        self.horizontalLayout_3.addLayout(self._2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.line = QtGui.QFrame(self.tab)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_5.addWidget(self.line)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_5 = QtGui.QLabel(self.tab)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        spacerItem = QtGui.QSpacerItem(408, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.pushButtonClearRx = QtGui.QPushButton(self.tab)
        self.pushButtonClearRx.setObjectName("pushButtonClearRx")
        self.horizontalLayout_2.addWidget(self.pushButtonClearRx)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.textEditRx = QtGui.QTextEdit(self.tab)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(50)
        font.setBold(False)
        self.textEditRx.setFont(font)
        self.textEditRx.setReadOnly(True)
        self.textEditRx.setObjectName("textEditRx")
        self.verticalLayout_5.addWidget(self.textEditRx)
        self.line_3 = QtGui.QFrame(self.tab)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_5.addWidget(self.line_3)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_8 = QtGui.QLabel(self.tab)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_6.addWidget(self.label_8)
        spacerItem1 = QtGui.QSpacerItem(408, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.pushButtonClearTx = QtGui.QPushButton(self.tab)
        self.pushButtonClearTx.setObjectName("pushButtonClearTx")
        self.horizontalLayout_6.addWidget(self.pushButtonClearTx)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.textEditTx = QtGui.QTextEdit(self.tab)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(50)
        font.setBold(False)
        self.textEditTx.setFont(font)
        self.textEditTx.setReadOnly(True)
        self.textEditTx.setObjectName("textEditTx")
        self.verticalLayout_5.addWidget(self.textEditTx)
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.tab_3)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_9 = QtGui.QLabel(self.tab_3)
        self.label_9.setMinimumSize(QtCore.QSize(100, 0))
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_10.addWidget(self.label_9)
        self.comboBoxCmd = QtGui.QComboBox(self.tab_3)
        self.comboBoxCmd.setMinimumSize(QtCore.QSize(120, 25))
        self.comboBoxCmd.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.comboBoxCmd.setObjectName("comboBoxCmd")
        self.comboBoxCmd.addItem("")
        self.comboBoxCmd.addItem("")
        self.comboBoxCmd.addItem("")
        self.comboBoxCmd.addItem("")
        self.comboBoxCmd.addItem("")
        self.comboBoxCmd.addItem("")
        self.comboBoxCmd.addItem("")
        self.comboBoxCmd.addItem("")
        self.comboBoxCmd.addItem("")
        self.comboBoxCmd.addItem("")
        self.comboBoxCmd.addItem("")
        self.comboBoxCmd.addItem("")
        self.comboBoxCmd.addItem("")
        self.comboBoxCmd.addItem("")
        self.comboBoxCmd.addItem("")
        self.comboBoxCmd.addItem("")
        self.comboBoxCmd.addItem("")
        self.comboBoxCmd.addItem("")
        self.comboBoxCmd.addItem("")
        self.comboBoxCmd.addItem("")
        self.horizontalLayout_10.addWidget(self.comboBoxCmd)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem2)
        self.verticalLayout_12.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_10 = QtGui.QLabel(self.tab_3)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_7.addWidget(self.label_10)
        self.lineEditStartByte = QtGui.QLineEdit(self.tab_3)
        self.lineEditStartByte.setReadOnly(True)
        self.lineEditStartByte.setObjectName("lineEditStartByte")
        self.verticalLayout_7.addWidget(self.lineEditStartByte)
        self.horizontalLayout_9.addLayout(self.verticalLayout_7)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_11 = QtGui.QLabel(self.tab_3)
        self.label_11.setObjectName("label_11")
        self.verticalLayout.addWidget(self.label_11)
        self.lineEditSizeByte = QtGui.QLineEdit(self.tab_3)
        self.lineEditSizeByte.setReadOnly(True)
        self.lineEditSizeByte.setObjectName("lineEditSizeByte")
        self.verticalLayout.addWidget(self.lineEditSizeByte)
        self.horizontalLayout_9.addLayout(self.verticalLayout)
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_12 = QtGui.QLabel(self.tab_3)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_8.addWidget(self.label_12)
        self.lineEditCmdId = QtGui.QLineEdit(self.tab_3)
        self.lineEditCmdId.setReadOnly(True)
        self.lineEditCmdId.setObjectName("lineEditCmdId")
        self.verticalLayout_8.addWidget(self.lineEditCmdId)
        self.horizontalLayout_9.addLayout(self.verticalLayout_8)
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.labelPayload = QtGui.QLabel(self.tab_3)
        self.labelPayload.setObjectName("labelPayload")
        self.verticalLayout_9.addWidget(self.labelPayload)
        self.lineEditUserPayload = QtGui.QLineEdit(self.tab_3)
        self.lineEditUserPayload.setAutoFillBackground(False)
        self.lineEditUserPayload.setMaxLength(236)
        self.lineEditUserPayload.setObjectName("lineEditUserPayload")
        self.verticalLayout_9.addWidget(self.lineEditUserPayload)
        self.horizontalLayout_9.addLayout(self.verticalLayout_9)
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_13 = QtGui.QLabel(self.tab_3)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_10.addWidget(self.label_13)
        self.lineEditCRC = QtGui.QLineEdit(self.tab_3)
        self.lineEditCRC.setReadOnly(True)
        self.lineEditCRC.setObjectName("lineEditCRC")
        self.verticalLayout_10.addWidget(self.lineEditCRC)
        self.horizontalLayout_9.addLayout(self.verticalLayout_10)
        self.verticalLayout_12.addLayout(self.horizontalLayout_9)
        self.stackedWidget = QtGui.QStackedWidget(self.tab_3)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtGui.QWidget()
        self.page.setObjectName("page")
        self.stackedWidget.addWidget(self.page)
        self.twoByteCmd = QtGui.QWidget()
        self.twoByteCmd.setObjectName("twoByteCmd")
        self.label_26 = QtGui.QLabel(self.twoByteCmd)
        self.label_26.setGeometry(QtCore.QRect(20, 0, 121, 16))
        self.label_26.setObjectName("label_26")
        self.comboBoxCmdOption = QtGui.QComboBox(self.twoByteCmd)
        self.comboBoxCmdOption.setGeometry(QtCore.QRect(10, 20, 256, 26))
        self.comboBoxCmdOption.setObjectName("comboBoxCmdOption")
        self.stackedWidget.addWidget(self.twoByteCmd)
        self.threeByteCmd = QtGui.QWidget()
        self.threeByteCmd.setObjectName("threeByteCmd")
        self.label3Byte = QtGui.QLabel(self.threeByteCmd)
        self.label3Byte.setGeometry(QtCore.QRect(20, 0, 151, 16))
        self.label3Byte.setLineWidth(3)
        self.label3Byte.setObjectName("label3Byte")
        self.lineEditThisAddress = QtGui.QLineEdit(self.threeByteCmd)
        self.lineEditThisAddress.setGeometry(QtCore.QRect(20, 20, 311, 22))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditThisAddress.sizePolicy().hasHeightForWidth())
        self.lineEditThisAddress.setSizePolicy(sizePolicy)
        self.lineEditThisAddress.setMinimumSize(QtCore.QSize(120, 0))
        self.lineEditThisAddress.setWhatsThis("")
        self.lineEditThisAddress.setObjectName("lineEditThisAddress")
        self.stackedWidget.addWidget(self.threeByteCmd)
        self.fourByteCmd = QtGui.QWidget()
        self.fourByteCmd.setObjectName("fourByteCmd")
        self.label_28 = QtGui.QLabel(self.fourByteCmd)
        self.label_28.setGeometry(QtCore.QRect(20, 0, 201, 16))
        self.label_28.setLineWidth(3)
        self.label_28.setObjectName("label_28")
        self.lineEditSleep = QtGui.QLineEdit(self.fourByteCmd)
        self.lineEditSleep.setGeometry(QtCore.QRect(20, 20, 131, 22))
        self.lineEditSleep.setInputMask("")
        self.lineEditSleep.setObjectName("lineEditSleep")
        self.stackedWidget.addWidget(self.fourByteCmd)
        self.UART = QtGui.QWidget()
        self.UART.setObjectName("UART")
        self.layoutWidget = QtGui.QWidget(self.UART)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 10, 381, 51))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_3 = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_15 = QtGui.QLabel(self.layoutWidget)
        self.label_15.setObjectName("label_15")
        self.gridLayout_3.addWidget(self.label_15, 0, 0, 1, 1)
        self.label_16 = QtGui.QLabel(self.layoutWidget)
        self.label_16.setObjectName("label_16")
        self.gridLayout_3.addWidget(self.label_16, 0, 1, 1, 1)
        self.label_17 = QtGui.QLabel(self.layoutWidget)
        self.label_17.setObjectName("label_17")
        self.gridLayout_3.addWidget(self.label_17, 0, 2, 1, 1)
        self.label_18 = QtGui.QLabel(self.layoutWidget)
        self.label_18.setObjectName("label_18")
        self.gridLayout_3.addWidget(self.label_18, 0, 3, 1, 1)
        self.comboBoxDataBits = QtGui.QComboBox(self.layoutWidget)
        self.comboBoxDataBits.setMinimumSize(QtCore.QSize(0, 25))
        self.comboBoxDataBits.setObjectName("comboBoxDataBits")
        self.gridLayout_3.addWidget(self.comboBoxDataBits, 1, 0, 1, 1)
        self.comboBoxParity = QtGui.QComboBox(self.layoutWidget)
        self.comboBoxParity.setMinimumSize(QtCore.QSize(0, 25))
        self.comboBoxParity.setObjectName("comboBoxParity")
        self.gridLayout_3.addWidget(self.comboBoxParity, 1, 1, 1, 1)
        self.comboBoxStopBits = QtGui.QComboBox(self.layoutWidget)
        self.comboBoxStopBits.setMinimumSize(QtCore.QSize(0, 25))
        self.comboBoxStopBits.setObjectName("comboBoxStopBits")
        self.gridLayout_3.addWidget(self.comboBoxStopBits, 1, 2, 1, 1)
        self.comboBoxBaudRate = QtGui.QComboBox(self.layoutWidget)
        self.comboBoxBaudRate.setMinimumSize(QtCore.QSize(0, 25))
        self.comboBoxBaudRate.setObjectName("comboBoxBaudRate")
        self.gridLayout_3.addWidget(self.comboBoxBaudRate, 1, 3, 1, 1)
        self.stackedWidget.addWidget(self.UART)
        self.Data = QtGui.QWidget()
        self.Data.setObjectName("Data")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.Data)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_19 = QtGui.QLabel(self.Data)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_2.addWidget(self.label_19)
        self.lineEditDestAddr = QtGui.QLineEdit(self.Data)
        self.lineEditDestAddr.setObjectName("lineEditDestAddr")
        self.verticalLayout_2.addWidget(self.lineEditDestAddr)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_20 = QtGui.QLabel(self.Data)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_3.addWidget(self.label_20)
        self.comboBoxOptions = QtGui.QComboBox(self.Data)
        self.comboBoxOptions.setObjectName("comboBoxOptions")
        self.comboBoxOptions.addItem("")
        self.comboBoxOptions.addItem("")
        self.comboBoxOptions.addItem("")
        self.verticalLayout_3.addWidget(self.comboBoxOptions)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_21 = QtGui.QLabel(self.Data)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_4.addWidget(self.label_21)
        self.comboBoxHandle = QtGui.QComboBox(self.Data)
        self.comboBoxHandle.setObjectName("comboBoxHandle")
        self.verticalLayout_4.addWidget(self.comboBoxHandle)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        spacerItem3 = QtGui.QSpacerItem(188, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        spacerItem4 = QtGui.QSpacerItem(20, 46, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem4)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.progressBar = QtGui.QProgressBar(self.Data)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_4.addWidget(self.progressBar)
        self.pushButtonClear = QtGui.QPushButton(self.Data)
        self.pushButtonClear.setObjectName("pushButtonClear")
        self.horizontalLayout_4.addWidget(self.pushButtonClear)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        spacerItem5 = QtGui.QSpacerItem(20, 48, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem5)
        self.stackedWidget.addWidget(self.Data)
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName("page_2")
        self.lineEditSecurity = QtGui.QLineEdit(self.page_2)
        self.lineEditSecurity.setGeometry(QtCore.QRect(10, 30, 391, 20))
        self.lineEditSecurity.setObjectName("lineEditSecurity")
        self.label = QtGui.QLabel(self.page_2)
        self.label.setGeometry(QtCore.QRect(10, 10, 491, 16))
        self.label.setObjectName("label")
        self.stackedWidget.addWidget(self.page_2)
        self.verticalLayout_12.addWidget(self.stackedWidget)
        self.label_23 = QtGui.QLabel(self.tab_3)
        self.label_23.setObjectName("label_23")
        self.verticalLayout_12.addWidget(self.label_23)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.lineEditFrameToSend = QtGui.QLineEdit(self.tab_3)
        self.lineEditFrameToSend.setReadOnly(True)
        self.lineEditFrameToSend.setObjectName("lineEditFrameToSend")
        self.horizontalLayout_8.addWidget(self.lineEditFrameToSend)
        self.pushButtonTxFrame = QtGui.QPushButton(self.tab_3)
        self.pushButtonTxFrame.setEnabled(True)
        self.pushButtonTxFrame.setMinimumSize(QtCore.QSize(110, 28))
        self.pushButtonTxFrame.setObjectName("pushButtonTxFrame")
        self.horizontalLayout_8.addWidget(self.pushButtonTxFrame)
        self.verticalLayout_12.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_25 = QtGui.QLabel(self.tab_3)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_7.addWidget(self.label_25)
        spacerItem6 = QtGui.QSpacerItem(387, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem6)
        self.pushButtonClearRf = QtGui.QPushButton(self.tab_3)
        self.pushButtonClearRf.setObjectName("pushButtonClearRf")
        self.horizontalLayout_7.addWidget(self.pushButtonClearRf)
        self.verticalLayout_12.addLayout(self.horizontalLayout_7)
        self.textEditRfResponse = QtGui.QTextEdit(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(50)
        font.setBold(False)
        self.textEditRfResponse.setFont(font)
        self.textEditRfResponse.setReadOnly(True)
        self.textEditRfResponse.setObjectName("textEditRfResponse")
        self.verticalLayout_12.addWidget(self.textEditRfResponse)
        self.tabWidget.addTab(self.tab_3, "")
        self.verticalLayout_11.addWidget(self.tabWidget)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem7 = QtGui.QSpacerItem(468, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem7)
        self.exitButton = QtGui.QPushButton(self.centralwidget)
        self.exitButton.setObjectName("exitButton")
        self.horizontalLayout_5.addWidget(self.exitButton)
        self.verticalLayout_11.addLayout(self.horizontalLayout_5)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 583, 21))
        self.menubar.setObjectName("menubar")
        self.menuRB_Commander = QtGui.QMenu(self.menubar)
        self.menuRB_Commander.setObjectName("menuRB_Commander")
        self.menuAbout = QtGui.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuRB_Commander.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.stackedWidget.setCurrentIndex(2)
        QtCore.QObject.connect(self.exitButton, QtCore.SIGNAL("clicked()"), MainWindow.close)
        QtCore.QObject.connect(self.comboBoxCmd, QtCore.SIGNAL("currentIndexChanged(QString)"), self.statusbar.clearMessage)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Radio Block Commander", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "COM Port", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "BAUD Rate", None, QtGui.QApplication.UnicodeUTF8))
        self.openComButton.setToolTip(QtGui.QApplication.translate("MainWindow", "additonal settings are \'8,N,1\'...", None, QtGui.QApplication.UnicodeUTF8))
        self.openComButton.setText(QtGui.QApplication.translate("MainWindow", "Open COM Port", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Serial RX", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonClearRx.setText(QtGui.QApplication.translate("MainWindow", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Serial TX", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonClearTx.setText(QtGui.QApplication.translate("MainWindow", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "COM Port", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Command Selection:", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxCmd.setItemText(0, QtGui.QApplication.translate("MainWindow", "test_request", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxCmd.setItemText(1, QtGui.QApplication.translate("MainWindow", "reset_request", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxCmd.setItemText(2, QtGui.QApplication.translate("MainWindow", "settings_request", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxCmd.setItemText(3, QtGui.QApplication.translate("MainWindow", "sleep_request", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxCmd.setItemText(4, QtGui.QApplication.translate("MainWindow", "send_data_request", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxCmd.setItemText(5, QtGui.QApplication.translate("MainWindow", "get_address_request", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxCmd.setItemText(6, QtGui.QApplication.translate("MainWindow", "get_panid_request", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxCmd.setItemText(7, QtGui.QApplication.translate("MainWindow", "get_channel_request", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxCmd.setItemText(8, QtGui.QApplication.translate("MainWindow", "get_receiver_state_request", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxCmd.setItemText(9, QtGui.QApplication.translate("MainWindow", "get_transmit_power_request", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxCmd.setItemText(10, QtGui.QApplication.translate("MainWindow", "get_ack_state_request", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxCmd.setItemText(11, QtGui.QApplication.translate("MainWindow", "set_uart_mode", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxCmd.setItemText(12, QtGui.QApplication.translate("MainWindow", "set_address_request", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxCmd.setItemText(13, QtGui.QApplication.translate("MainWindow", "set_panid_request", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxCmd.setItemText(14, QtGui.QApplication.translate("MainWindow", "set_channel_request", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxCmd.setItemText(15, QtGui.QApplication.translate("MainWindow", "set_receiver_state_request", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxCmd.setItemText(16, QtGui.QApplication.translate("MainWindow", "set_transmit_power_request", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxCmd.setItemText(17, QtGui.QApplication.translate("MainWindow", "set_security_key_request", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxCmd.setItemText(18, QtGui.QApplication.translate("MainWindow", "set_ack_state_request", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxCmd.setItemText(19, QtGui.QApplication.translate("MainWindow", "set_led_state_request", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "Start Byte", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEditStartByte.setText(QtGui.QApplication.translate("MainWindow", "0xAB", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "Size", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "CMD ID", None, QtGui.QApplication.UnicodeUTF8))
        self.labelPayload.setText(QtGui.QApplication.translate("MainWindow", "Payload                                                                        ", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEditUserPayload.setToolTip(QtGui.QApplication.translate("MainWindow", "\"You must press enter to complete building the data request!\"", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("MainWindow", "CRC", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("MainWindow", "Command Option:", None, QtGui.QApplication.UnicodeUTF8))
        self.label3Byte.setText(QtGui.QApplication.translate("MainWindow", "This Node\'s Address:", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEditThisAddress.setToolTip(QtGui.QApplication.translate("MainWindow", "Enter an address in the form \'12CD\', then press the Enter Key!", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setText(QtGui.QApplication.translate("MainWindow", "Sleep Interval (milliseconds):", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEditSleep.setToolTip(QtGui.QApplication.translate("MainWindow", "Enter the number of miliseconds to sleep.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("MainWindow", "Data Bits", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("MainWindow", "Parity", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("MainWindow", "Stop Bits", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("MainWindow", "Baud Rate", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("MainWindow", "Destination Address", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("MainWindow", "Options", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxOptions.setItemText(0, QtGui.QApplication.translate("MainWindow", "ack", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxOptions.setItemText(1, QtGui.QApplication.translate("MainWindow", "none", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxOptions.setItemText(2, QtGui.QApplication.translate("MainWindow", "security", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("MainWindow", "Handle", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonClear.setText(QtGui.QApplication.translate("MainWindow", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Security key (enter an Ascii string of length 16 or a hexadecimal string of lengh 32 preceded by \"0x\")", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("MainWindow", "Serial fame to send:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonTxFrame.setText(QtGui.QApplication.translate("MainWindow", "Send Frame", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("MainWindow", "RadioBlock Response:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonClearRf.setText(QtGui.QApplication.translate("MainWindow", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("MainWindow", "Command Frame Constructor", None, QtGui.QApplication.UnicodeUTF8))
        self.exitButton.setToolTip(QtGui.QApplication.translate("MainWindow", "additonal settings are \'8,N,1\'...", None, QtGui.QApplication.UnicodeUTF8))
        self.exitButton.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.menuRB_Commander.setTitle(QtGui.QApplication.translate("MainWindow", "Com Port", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAbout.setTitle(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

